name: CI

on:
  push:
    branches:
      - '**'
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Decrypt GPG file
        uses: actions/checkout@v2
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output  ${GITHUB_WORKSPACE}/dev.adminUserLoginCookiesFromCypress.json ${GITHUB_WORKSPACE}/dev.adminUserLoginCookiesFromCypress.json.gpg
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Run Tests
        run: npm run cypress:f

  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
